kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: blue-green-route
  annotations:
    haproxy.router.openshift.io/disable_cookies: 'true'
    haproxy.router.openshift.io/balance: 'roundrobin'
spec:
  to:
    kind: Service
    name: user{n}-hello-chart-service
    weight: 90
  alternateBackends:
  - kind: Service
    name: user1-hello-world
    weight: 10