ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/talushcohen/repo1'
  tag: 'chart_v1'

service:
  servicePort: 8080
probes:
  readiness:
    path: /health/readiness
    initialDelaySeconds: 1 # the time is waiting befor testing the application path
    timeoutSeconds: 1 # the time for timeout
    periodSeconds: 10 # the abount of time to wait between checks
    successThreshold: 1 # count to decalre seccessfull 
    failureThreshold: 3 # count to decalre failure 
  liveness:
    path: /health/liveliness
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
volume:
  mount:
    path: /tmp/html
test: Healty
github:
  user: talushcohen
  token: empty-pass
  url: https://api.github.com/repos/talushcohen/AppDeployCourse/issues


